locales = [ "de", "fy-NL", "nl",]
[[paths]]
reference = "templates/pages/homepage/campaigns/tiktok-bring-in-ad-transparency-now.pot"
l10n = "locales/{locale}/pages/homepage/campaigns/tiktok-bring-in-ad-transparency-now.po"
locales = [ "de",]

[[paths]]
reference = "templates/snippets/wagtailpages.Petition/90-tiktok-petition.pot"
l10n = "locales/{locale}/snippets/wagtailpages.Petition/90-tiktok-petition.po"
locales = [ "de",]

[[paths]]
reference = "templates/snippets/wagtailpages.DonationModal/1-privacy_donate_modal.pot"
l10n = "locales/{locale}/snippets/wagtailpages.DonationModal/1-privacy_donate_modal.po"
locales = [ "de",]

[[paths]]
reference = "templates/pages/homepage.pot"
l10n = "locales/{locale}/pages/homepage.po"
locales = [ "de",]

[[paths]]
reference = "templates/pages/homepage/what-we-do.pot"
l10n = "locales/{locale}/pages/homepage/what-we-do.po"
locales = [ "de",]

[[paths]]
reference = "templates/snippets/wagtailpages.FocusArea/1-rally-citizens.pot"
l10n = "locales/{locale}/snippets/wagtailpages.FocusArea/1-rally-citizens.po"
locales = [ "de",]

[[paths]]
reference = "templates/snippets/wagtailpages.FocusArea/2-connect-leaders.pot"
l10n = "locales/{locale}/snippets/wagtailpages.FocusArea/2-connect-leaders.po"
locales = [ "de",]

[[paths]]
reference = "templates/snippets/wagtailpages.FocusArea/3-shape-the-agenda.pot"
l10n = "locales/{locale}/snippets/wagtailpages.FocusArea/3-shape-the-agenda.po"
locales = [ "de",]

