locales = [ "de", "es", "fr", "fy-NL", "nl", "pl", "pt-BR",]
[[paths]]
reference = "templates/pages/homepage/what-we-fund.pot"
l10n = "locales/{locale}/pages/homepage/what-we-fund.po"
locales = [ "de", "es", "fr",]

[[paths]]
reference = "templates/pages/homepage/what-we-do.pot"
l10n = "locales/{locale}/pages/homepage/what-we-do.po"
locales = [ "de", "es", "fr", "fy-NL", "nl", "pt-BR",]

