locales = [ "de", "es", "fr", "fy-NL", "nl", "pl", "pt-BR",]
[[paths]]
reference = "templates/snippets/wagtailpages.BuyersGuideProductCategory/7-valentines-day.pot"
l10n = "locales/{locale}/snippets/wagtailpages.BuyersGuideProductCategory/7-valentines-day.po"
locales = [ "fr",]

