locales = [ "de", "fy-NL", "nl",]
[[paths]]
reference = "templates/pages/homepage/campaigns/tiktok-bring-in-ad-transparency-now.pot"
l10n = "locales/{locale}/pages/homepage/campaigns/tiktok-bring-in-ad-transparency-now.po"
locales = [ "de",]

[[paths]]
reference = "templates/snippets/wagtailpages.Petition/90-tiktok-petition.pot"
l10n = "locales/{locale}/snippets/wagtailpages.Petition/90-tiktok-petition.po"
locales = [ "de",]

[[paths]]
reference = "templates/snippets/wagtailpages.DonationModal/1-privacy_donate_modal.pot"
l10n = "locales/{locale}/snippets/wagtailpages.DonationModal/1-privacy_donate_modal.po"
locales = [ "de",]

