locales = [ "de", "es", "fr", "fy-NL", "nl", "pl", "pt-BR",]
[[paths]]
reference = "templates/pages/homepage/campaigns/tiktok-bring-in-ad-transparency-now.pot"
l10n = "locales/{locale}/pages/homepage/campaigns/tiktok-bring-in-ad-transparency-now.po"
locales = [ "de",]

[[paths]]
reference = "templates/snippets/wagtailpages.Petition/90-tiktok-petition.pot"
l10n = "locales/{locale}/snippets/wagtailpages.Petition/90-tiktok-petition.po"
locales = [ "de",]

[[paths]]
reference = "templates/snippets/wagtailpages.DonationModal/1-privacy_donate_modal.pot"
l10n = "locales/{locale}/snippets/wagtailpages.DonationModal/1-privacy_donate_modal.po"
locales = [ "de",]

[[paths]]
reference = "templates/pages/homepage.pot"
l10n = "locales/{locale}/pages/homepage.po"
locales = [ "de", "fr",]

[[paths]]
reference = "templates/pages/homepage/what-we-do.pot"
l10n = "locales/{locale}/pages/homepage/what-we-do.po"
locales = [ "de", "fr",]

[[paths]]
reference = "templates/snippets/wagtailpages.FocusArea/1-rally-citizens.pot"
l10n = "locales/{locale}/snippets/wagtailpages.FocusArea/1-rally-citizens.po"
locales = [ "de", "fr",]

[[paths]]
reference = "templates/snippets/wagtailpages.FocusArea/2-connect-leaders.pot"
l10n = "locales/{locale}/snippets/wagtailpages.FocusArea/2-connect-leaders.po"
locales = [ "de", "fr",]

[[paths]]
reference = "templates/snippets/wagtailpages.FocusArea/3-shape-the-agenda.pot"
l10n = "locales/{locale}/snippets/wagtailpages.FocusArea/3-shape-the-agenda.po"
locales = [ "de", "fr",]

[[paths]]
reference = "templates/pages/homepage/blog/zoom-makes-right-call-encryption.pot"
l10n = "locales/{locale}/pages/homepage/blog/zoom-makes-right-call-encryption.po"
locales = [ "de",]

[[paths]]
reference = "templates/pages/homepage/blog/tips-make-your-zoom-gatherings-more-private.pot"
l10n = "locales/{locale}/pages/homepage/blog/tips-make-your-zoom-gatherings-more-private.po"
locales = [ "de",]

[[paths]]
reference = "templates/pages/homepage/privacynotincluded/happn.pot"
l10n = "locales/{locale}/pages/homepage/privacynotincluded/happn.po"
locales = [ "de",]

