locales = [ "de", "es", "fr", "fy-NL", "nl", "pl", "pt-BR",]
[[paths]]
reference = "templates/pages/homepage/blog/mozilla-investigation-youtube-algorithm-recommends-videos-that-violate-the-platforms-very-own-policies.pot"
l10n = "locales/{locale}/pages/homepage/blog/mozilla-investigation-youtube-algorithm-recommends-videos-that-violate-the-platforms-very-own-policies.po"
locales = [ "de",]

[[paths]]
reference = "templates/snippets/wagtailpages.BuyersGuideProductCategory/11-dating-apps.pot"
l10n = "locales/{locale}/snippets/wagtailpages.BuyersGuideProductCategory/11-dating-apps.po"
locales = [ "de", "es", "fr", "fy-NL", "nl", "pl", "pt-BR",]

[[paths]]
reference = "templates/snippets/wagtailpages.BuyersGuideProductCategory/6-pets.pot"
l10n = "locales/{locale}/snippets/wagtailpages.BuyersGuideProductCategory/6-pets.po"
locales = [ "de", "es", "fr", "fy-NL", "nl", "pl", "pt-BR",]

[[paths]]
reference = "templates/snippets/wagtailpages.BuyersGuideProductCategory/7-valentines-day.pot"
l10n = "locales/{locale}/snippets/wagtailpages.BuyersGuideProductCategory/7-valentines-day.po"
locales = [ "de", "es", "fr", "fy-NL", "nl", "pl", "pt-BR",]

[[paths]]
reference = "templates/pages/homepage/blog/what-is-the-digital-divide-mozilla-explains.pot"
l10n = "locales/{locale}/pages/homepage/blog/what-is-the-digital-divide-mozilla-explains.po"
locales = [ "de", "es", "fr", "pl", "pt-BR",]

[[paths]]
reference = "templates/snippets/wagtailpages.BuyersGuideProductCategory/3-entertainment.pot"
l10n = "locales/{locale}/snippets/wagtailpages.BuyersGuideProductCategory/3-entertainment.po"
locales = [ "de", "es", "fr", "fy-NL", "nl", "pl", "pt-BR",]

[[paths]]
reference = "templates/pages/homepage/blog/who-cares-about-my-data-mozilla-explains-data-protection.pot"
l10n = "locales/{locale}/pages/homepage/blog/who-cares-about-my-data-mozilla-explains-data-protection.po"
locales = [ "de", "es", "fr", "pl", "pt-BR",]

[[paths]]
reference = "templates/snippets/wagtailpages.BuyersGuideProductCategory/12-sex-toys.pot"
l10n = "locales/{locale}/snippets/wagtailpages.BuyersGuideProductCategory/12-sex-toys.po"
locales = [ "de", "es", "fr", "fy-NL", "nl", "pl", "pt-BR",]

[[paths]]
reference = "templates/snippets/wagtailpages.BuyersGuideProductCategory/5-health-exercise.pot"
l10n = "locales/{locale}/snippets/wagtailpages.BuyersGuideProductCategory/5-health-exercise.po"
locales = [ "de", "es", "fr", "fy-NL", "nl", "pl", "pt-BR",]

[[paths]]
reference = "templates/snippets/wagtailpages.BuyersGuideProductCategory/2-smart-home.pot"
l10n = "locales/{locale}/snippets/wagtailpages.BuyersGuideProductCategory/2-smart-home.po"
locales = [ "de", "es", "fr", "fy-NL", "nl", "pl", "pt-BR",]

[[paths]]
reference = "templates/snippets/wagtailpages.BuyersGuideProductCategory/8-video-call-apps.pot"
l10n = "locales/{locale}/snippets/wagtailpages.BuyersGuideProductCategory/8-video-call-apps.po"
locales = [ "de", "es", "fr", "fy-NL", "nl", "pl", "pt-BR",]

[[paths]]
reference = "templates/pages/homepage/campaigns/regrets-reporter/findings.pot"
l10n = "locales/{locale}/pages/homepage/campaigns/regrets-reporter/findings.po"
locales = [ "de", "es", "fr", "nl", "pt-BR",]

[[paths]]
reference = "templates/snippets/wagtailpages.BuyersGuideProductCategory/4-wearables.pot"
l10n = "locales/{locale}/snippets/wagtailpages.BuyersGuideProductCategory/4-wearables.po"
locales = [ "de", "es", "fr", "fy-NL", "nl", "pl", "pt-BR",]

[[paths]]
reference = "templates/snippets/wagtailpages.BuyersGuideProductCategory/10-best-of.pot"
l10n = "locales/{locale}/snippets/wagtailpages.BuyersGuideProductCategory/10-best-of.po"
locales = [ "de", "es", "fr", "fy-NL", "nl", "pl", "pt-BR",]

[[paths]]
reference = "templates/snippets/wagtailpages.BuyersGuideProductCategory/9-home-office.pot"
l10n = "locales/{locale}/snippets/wagtailpages.BuyersGuideProductCategory/9-home-office.po"
locales = [ "de", "es", "fr", "fy-NL", "nl", "pl", "pt-BR",]

[[paths]]
reference = "templates/snippets/wagtailpages.BuyersGuideProductCategory/1-toys-games.pot"
l10n = "locales/{locale}/snippets/wagtailpages.BuyersGuideProductCategory/1-toys-games.po"
locales = [ "de", "es", "fr", "fy-NL", "nl", "pl", "pt-BR",]

[[paths]]
reference = "templates/pages/homepage/blog/will-big-tech-stop-election-disinformation-in-germany.pot"
l10n = "locales/{locale}/pages/homepage/blog/will-big-tech-stop-election-disinformation-in-germany.po"
locales = [ "de",]

[[paths]]
reference = "templates/pages/homepage/campaigns/german-election.pot"
l10n = "locales/{locale}/pages/homepage/campaigns/german-election.po"
locales = [ "de",]

